service: willarrivein-service

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  router:
    handler: api/router.handler
    environment:
      WAI_MTA_API_KEY: '${param:WAI_MTA_API_KEY}'
    events:
      - http:
          path: /
          method: get
